package org.monarchinitiative.lirical.core.likelihoodratio;

public enum LrMatchType {
    EXACT_MATCH,
    QUERY_TERM_SUBCLASS_OF_DISEASE_TERM,
    QUERY_TERM_PRESENT_BUT_EXCLUDED_IN_DISEASE,
    DISEASE_TERM_SUBCLASS_OF_QUERY,
    NON_ROOT_COMMON_ANCESTOR,
    UNUSUAL_BACKGROUND_FREQUENCY,
    EXCLUDED_QUERY_TERM_NOT_PRESENT_IN_DISEASE,
    EXCLUDED_QUERY_TERM_EXCLUDED_IN_DISEASE,
    EXCLUDED_QUERY_TERM_PRESENT_IN_DISEASE,
    NO_MATCH_BELOW_ROOT
}
