package org.monarchinitiative.lirical.exomiser_db_adapter;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.monarchinitiative.lirical.core.model.GenomeBuild;
import org.monarchinitiative.lirical.core.service.VariantMetadataService;

import java.nio.file.Path;
import java.util.Map;
import java.util.Optional;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

public class ExomiserMvStoreMetadataServiceFactoryTest {

    private static final Path TESTDATA_DIR = Path.of("src/test/resources/testdata");

    /**
     * Tests for databases generated by `lirical==[2.0.0,2.3.0]`.
     */
    @Nested
    public class LiricalV200_230 {
        private ExomiserMvStoreMetadataServiceFactory factory;

        @BeforeEach
        public void setUp() {
            Map<GenomeBuild, ExomiserResources> resources = Map.of(
                    GenomeBuild.HG38,
                    new ExomiserResources(
                            TESTDATA_DIR.resolve("9999_hg38_variants.mv.db"),
                            TESTDATA_DIR.resolve("9999_hg38_clinvar.mv.db")
                    )
            );

            factory = ExomiserMvStoreMetadataServiceFactory.fromResources(resources);
        }

        @AfterEach
        public void tearDown() {
            factory.close();
            factory = null;
        }

        @Test
        public void checkWeHaveTheServiceForHg38() {
            Optional<VariantMetadataService> vmso = factory.getVariantMetadataService(GenomeBuild.HG38);

            assertThat(vmso.isPresent(), equalTo(true));
        }

        @Test
        public void fetchLmnaMetadata() {
            VariantMetadataService service = factory.getVariantMetadataService(GenomeBuild.HG38).orElseThrow();

            VariantMetadataServiceTestUtil.testLmnaMetadata(service);
        }

        @Test
        public void fetchDmdMetadata() {
            VariantMetadataService service = factory.getVariantMetadataService(GenomeBuild.HG38).orElseThrow();

            VariantMetadataServiceTestUtil.testDmdMetadata(service);
        }
    }

    /**
     * Tests for databases generated by `lirical==[2.3.1,3.0.0)`.
     */
    @Nested
    public class LiricalV231_onwards {
        private ExomiserMvStoreMetadataServiceFactory factory;

        @BeforeEach
        public void setUp() {
            Map<GenomeBuild, ExomiserResources> resources = Map.of(
                    GenomeBuild.HG38,
                    new ExomiserResources(
                            TESTDATA_DIR.resolve("2512_hg38_variants.mini.mv.db"),
                            TESTDATA_DIR.resolve("2512_hg38_clinvar.mini.mv.db")
                    )
            );

            factory = ExomiserMvStoreMetadataServiceFactory.fromResources(resources);
        }

        @AfterEach
        public void tearDown() {
            factory.close();
            factory = null;
        }

        @Test
        public void checkWeHaveTheServiceForHg38() {
            Optional<VariantMetadataService> vmso = factory.getVariantMetadataService(GenomeBuild.HG38);

            assertThat(vmso.isPresent(), equalTo(true));
        }

        @Test
        public void fetchLmnaMetadata() {
            VariantMetadataService service = factory.getVariantMetadataService(GenomeBuild.HG38).orElseThrow();

            VariantMetadataServiceTestUtil.testLmnaMetadata(service);
        }

        @Test
        public void fetchDmdMetadata() {
            VariantMetadataService service = factory.getVariantMetadataService(GenomeBuild.HG38).orElseThrow();

            VariantMetadataServiceTestUtil.testDmdMetadata(service);
        }
    }

}